services:
  db:
    image: postgres
    restart: unless-stopped
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=data_quality
    ports:
      - '5432:5432'
    volumes:
      - ./db:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/create_tables.sql
  server:
    build:
      context: .
    ports:
      - 5000:5000
  mkdocs:
    build:
      dockerfile: ./mkdocs/Dockerfile
    ports:
      - 8000:8000
    stdin_open: true
    tty: true
