###################
### API SECTION ###
###################

## APIDAE
api:
  apiName: "apidae"
  url: "https://api.apidae-tourisme.cooking/api/v002/recherche/list-objets-touristiques"
  apiKey: "8uEnYKe1"
  projectId: "3628"
  searchId: "69700"
  count: "20"
  typeObjet: "RESTAURATION"
  content-type: "application/json"

## DATAtourisme
#api:
#  apiName: "datatourisme"
#  url: "https://www.data.gouv.fr/fr/datasets/r/56d437a7-eb0c-4c31-9138-539be94bc490"
#  content-type: "text/csv"

api:
  apiName: "local"
  file: "datatourisme-reg-pdl.csv"
  content-type: "text/csv"

###################
### API SECTION ###
###################

postgresql:
  database: "data_quality"
  table: "soda_results"
  column: "results"
  user: "postgres"
  password: "secret"
  host: "127.0.0.1"
  port: "5432"

backend:
#   criteria: "criteria_apidae_restauration.json" # for apidae api
  criteria: "criteria_datatourisme_reg-pdl.json"

soda:
#  dataset_name: "restauration"
#  data_source_name: "apidae"
#  scan_definition_name: "niveau basique"
  dataset_name: "reg-pdl"
  data_source_name: "datatourisme"
  scan_definition_name: "niveau_basique"